// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgshqyxuewimyahqebcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnc2hxeXh1ZXdpbXlhaHFlYmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzQyMjksImV4cCI6MjA1Nzg1MDIyOX0.vKVwqYifJgs9HFmtKP_7bowz0AQYS792uG623M_W7kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);